# Generated by Django 5.0.4 on 2024-05-02 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'playlist_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('jumlah_lagu', models.IntegerField(default=0)),
                ('id_label', models.UUIDField()),
                ('total_durasi', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
            options={
                'db_table': 'konten',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=50)),
                ('id_pemilik_hak_cipta', models.UUIDField()),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='PemilikHakCipta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('rate_royalti', models.IntegerField()),
            ],
            options={
                'db_table': 'pemilik_hak_cipta',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Perempuan'), (1, 'Laki-laki')])),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('is_verified', models.BooleanField()),
                ('kota_asal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'akun',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='premium', serialize=False, to='registration.user')),
                ('rate_royalti', models.IntegerField()),
            ],
            options={
                'db_table': 'premium',
            },
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='podcaster', to='registration.user')),
            ],
            options={
                'db_table': 'podcaster',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('id_pemilik_hak_cipta', models.UUIDField()),
                ('email_akun', models.ForeignKey(db_column='email_akun', on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='registration.user')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('id_pemilik_hak_cipta', models.UUIDField()),
                ('email_akun', models.ForeignKey(db_column='email_akun', on_delete=django.db.models.deletion.CASCADE, related_name='songwriter', to='registration.user')),
            ],
            options={
                'db_table': 'songwriter',
            },
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id_user_playlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('jumlah_lagu', models.IntegerField()),
                ('tanggal_dibuat', models.DateField()),
                ('total_durasi', models.IntegerField(default=0)),
                ('email_pembuat', models.ForeignKey(db_column='email_pembuat', on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='registration.user')),
                ('id_playlist', models.ForeignKey(db_column='id_playlist', on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to='registration.playlist')),
            ],
            options={
                'db_table': 'user_playlist',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_konten', models.OneToOneField(db_column='id_konten', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='song', serialize=False, to='registration.konten')),
                ('total_play', models.IntegerField(default=0)),
                ('total_download', models.IntegerField(default=0)),
                ('id_album', models.ForeignKey(db_column='id_album', on_delete=django.db.models.deletion.CASCADE, related_name='song', to='registration.album')),
                ('id_artist', models.ForeignKey(db_column='id_artist', on_delete=django.db.models.deletion.CASCADE, related_name='song', to='registration.artist')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='AkunPlaySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateField()),
                ('email_pemain', models.ForeignKey(db_column='email_pemain', on_delete=django.db.models.deletion.CASCADE, related_name='akun_play_song', to='registration.user')),
                ('id_song', models.ForeignKey(db_column='id_song', on_delete=django.db.models.deletion.CASCADE, related_name='akun_play_song', to='registration.song')),
            ],
            options={
                'db_table': 'akun_play_song',
            },
        ),
    ]
